[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sgwt"
version = "0.2.4"
description = "Sparse Tools for the Spectral Graph Wavelet Transformation and Graph Convolution"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Luke Lowery"}]
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "scipy"
]

[tool.setuptools.package-data]
"sgwt.library" = [
    "dll/*.dll", 
    "dll/*.so", 
    "dll/*.dylib",
    "KERNELS/*.json",  # Kernels
    "SIGNALS/*.mat"    # SIGNALS
    "IMPEDANCE/*.mat", # Laplacians
    "LENGTH/*.mat",
    "DELAY/*.mat" ,

]

[tool.setuptools.packages.find]
where = [""]